valid_letters = %w(A AA AB ABC AC AE AG AH AI AL AM AN ANL AO AP AQ ARX AS AT AUG AW AWO AY AZ B BC BD BF BG BH BJ BL BM BN BP BQ BR BS BT BU BV BX C CB CC CD CE CG CIS CJ CMH CMM CN CR CS CT CZ D DA DAA DAW DB DC DD DE DF DFF DG DH DJ DJK DK DKJ DL DOC DP DQ DR DS DT DTH DU DX E EA EB EC ED EE EK EP EPA EX F FB FC FEM FG FJ FND FP FSD FT FUL G GA GB GC GDA GE GF GH GN GR GS GT GV H HA HB HC HCG HD HE HF HFS HG HH HHG HJ HJC HM HMK HN HQ HS HT HV HX I IA IB IID ILL ILM IN IOE IP J JA JAN JB JC JF JG JH JHE JJ JK JKC JL JLN JN JQ JS JV JX JZ K KB KBM KBP KBQ KBR KBU KC KD KDC KDE KDG KDK KDS KDZ KE KEA KEB KEM KEN KEO KEQ KES KF KFA KFC KFD KFF KFG KFH KFI KFK KFL KFM KFN KFO KFP KFR KFS KFT KFU KFV KFW KFX KFZ KG KGA KGB KGC KGD KGE KGF KGG KGH KGJ KGK KGL KGN KGQ KGS KGT KGV KGX KH KHA KHC KHD KHF KHH KHK KHP KHQ KHU KHW KIT KJ KJA KJC KJE KJG KJJ KJK KJM KJN KJP KJQ KJR KJS KJT KJV KJW KK KKA KKB KKC KKE KKF KKG KKH KKI KKJ KKM KKN KKP KKQ KKR KKS KKT KKV KKW KKX KKY KKZ KL KLA KLB KLD KLE KLF KLG KLH KLM KLN KLP KLR KLS KLT KLV KLW KM KMC KME KMF KMH KMJ KMK KML KMM KMN KMO KMP KMQ KMT KMU KMV KMX KN KNC KND KNE KNF KNG KNH KNK KNL KNM KNN KNP KNQ KNR KNS KNT KNU KNW KNX KNY KP KPA KPC KPE KPF KPG KPH KPJ KPK KPL KPM KPP KPS KPT KPV KPW KQ KQC KQE KQG KQJ KQK KQP KQW KRB KRC KRG KRM KRN KRP KRR KRS KRU KRV KRX KS KSA KSC KSH KSJ KSK KSL KSP KSS KST KSV KSW KSX KSY KTA KTD KTG KTJ KTK KTL KTQ KTR KTT KTU KTV KTW KTX KTY KTZ KU KUC KUQ KVC KVF KVM KVN KVP KVQ KVR KVS KVW KWC KWG KWH KWL KWP KWR KWW KWX KZ KZA KZD L LA LAW LB LC LD LE LF LG LH LJ LL LN LRM LT LV M MAY MB MC ME MF MH MKL ML MPC MR MS MT MY N NA NAT NAX NB NC ND NDA NDS NE NER NEW NG NH NK NL NMB NN NO NT NV NX OK ONC P PA PB PC PCR PD PE PF PG PH PHD PJ PJC PK PL PM PN PNB PP PQ PR PS PT PZ Q QA QB QC QD QE QH QK QL QM QP QR QRY QU QV R RA RB RBW RC RCC RD RE REF RES RF RG RH RJ RK RL RM RN RP RS RT RV RX RZ S SB SD SEE SF SFK SGV SH SK SN SQL SW T TA TC TD TDD TE TF TG TGG TH TJ TK TL TN TNJ TO TP TR TS TT TX TZ U UA UB UC UD UE UF UG UH UN USE V VA VB VC VD VE VF VG VK VLA VM W WQ X XP XX Y YH YL YY Z ZA ZHN ZZ ZZZ )
LETTER_INDEX = {}
valid_letters.each_with_index do |let, i|
  LETTER_INDEX[let] = i + 1
end


def hlb_comparitor(lc)
  
  # Turn the letters into their ascii numbers; assume three of them
  
  let = '%03d' % LETTER_INDEX[lc.letters]
  num = ('%010.4f' % lc.digits).gsub('.', '')
  if lc.firstcutter
    cutletter = lc.firstcutter.letter.ord - 64
    cutnum = '%05d' % lc.firstcutter.digits
  else
    cutnum = '0000000'
  end
  
  comparitor = [let,num,cutnum].join('').to_i
end
